services:
  tests:
    container_name: pytest-allure
    image: allure_app
    build:
      context: .
      dockerfile: Dockerfile

  allure:
    image: frankescobar/allure-docker-service
    container_name: allure-report
    ports:
      - "4040:4040"
    volumes:
      - ./allure-results:/app/allure-results
      - ./allure-report:/app/allure-report
    environment:
      CHECK_RESULTS_EVERY_SECONDS: 3
      KEEP_HISTORY: 1