name: Test and Deploy Allure Reports

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
        
    - name: Cache pip dependencies
      uses: actions/cache@v3
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-
          
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        
    - name: Run tests with pytest
      run: pytest --alluredir=allure-results
        
    - name: Generate Allure test report
      uses: andgineer/allure-report@v3.6
      id: allure-report
      with:
        allure-results: allure-results
        website: gh-pages-dir
        reports-site-path: builds/tests

    - name: Load test report history
      uses: actions/checkout@v3
      continue-on-error: true
      with:
        ref: gh-pages
        path: gh-pages

    - name: Build test report
      uses: simple-elf/allure-report-action@v1.7
      with:
        gh_pages: gh-pages
        allure_history: allure-history
        allure_results: build/allure-results

    - name: Publish test report
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_branch: gh-pages 
        publish_dir: ./allure-report