name: Run Tests, Generate Allure Report and deploy Allure Report to GitHub Pages

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - name: Cache pip dependencies
      uses: actions/cache@v3
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Install Allure CLI
      run: npm install -g allure-commandline --save-dev

    - name: Run tests with pytest
      run: pytest --alluredir=allure-results

    - name: Generate Allure report
      run: allure generate allure-results -o allure-report --clean

    - name: Upload allure results
      uses: actions/upload-artifact@v4
      with:
        name: allure-results
        path: allure-results/
    
    - name: Upload allure report
      uses: actions/upload-artifact@v4
      with:
        name: allure-report
        path: allure-report/
    
  build:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Download Allure report artifact
        uses: actions/download-artifact@v4
        with:
          name: allure-report
          path: ./allure-report

      - name: Setup Pages
        uses: actions/configure-pages@v5

      - name: Upload artifact for Pages
        uses: actions/upload-pages-artifact@v4
        with:
          path: ./allure-report

  # Deployment job
  deploy:
    needs: build
    runs-on: ubuntu-latest

    permissions:
      contents: read
      pages: write
      id-token: write

    concurrency:
      group: "pages"
      cancel-in-progress: false
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4